sudo: required

services:
  - docker

before_install:
  - docker build -t browserless/chrome:latest .

script:
  - docker run -it -e CI=true --entrypoint ./node_modules/.bin/jest browserless/chrome:latest --runInBand --bail --forceExit
