sudo: required

services:
  - docker

# Pinning chromium rev until it's stable for 2.1.x
before_install:
  - docker build -t browserless/chrome:latest .
  - docker build --build-arg "USE_CHROME_STABLE=true" -t browserless/chrome:stable .

script:
  - docker run -it -e CI=true --entrypoint ./test.sh browserless/chrome:latest
  - docker run -it -e CI=true --entrypoint ./test.sh browserless/chrome:stable
